/* eslint-disable */
declare module "@dhis2/ui";
declare module "@dhis2/d2-i18n";
declare module "*.module.css";
declare module "react-web-vitals";
declare module '@iapps/function-analytics';
declare module 'lodash';
declare module 'react-color';
declare module 'async/mapLimit';
declare module '@dhis2/analytics/build/cjs/components/TransferOption';
/* eslint-enable */